from . import hotel_room
from . import hotel_facility
from . import hotel_item
from . import hotel_category
from . import hotel_accommodation
from . import hotel_guest
from . import hotel_order
from . import hotel_kanban
from . import hotel_order_list
from . import hotel_payment
from . import hotel_payment_line
from . import hotel_guests