{
    'name': "Hotel Management",
    'version': '1.0',
    'depends': ['base','mail','account','sale','lunch','base_automation'],
    'author': "Author Name",
    'license':"",
    'category': 'Hotel Management',
    'sequence':-20,
    'description': """
    Description text
    """,
    'application': True,
    'installable': True,
    'data': [
        'security/hotel_management_groups.xml',
        'security/hotel_management_security.xml',
        'security/ir.model.access.csv',
        'report/hotel_management_report.xml',
        'report/hotel_management_report_template.xml',
        'data/hotel_management_data.xml',
        'data/hotel_management_sequence.xml',
        'data/email_action.xml',
        'views/hotel_room_views.xml',
        'views/hotel_facility_views.xml',
        'views/hotel_item_views.xml',
        'views/hotel_category_views.xml',
        'views/hotel_accommodation_views.xml',
        'views/hotel_order_views.xml',
        'views/hotel_kanban_views.xml',
        'views/hotel_guest_views.xml',
        'views/email_template_views.xml',
        'views/hotel_lunch_views.xml',
        'views/hotel_archive_views.xml',
        'views/hotel_report_views.xml',
        'views/hotel_management_menus.xml',
    ],
}